package Exercise2;

public class Colours extends javax.swing.JFrame
{
    private Gateway gateway = new Gateway();
    private boolean buttonPressed = false;
     private boolean buttonPressed2 = false;
      private boolean buttonPressed3 = false;
       private boolean buttonPressed4 = false;
        

    /** Creates new form Colours */
    public Colours()
    {
        initComponents();
        Palette parchis = new Palette();
        Painter p1 = new Painter(jButton1,parchis,gateway,1);
        Painter p2 = new Painter(jButton2,parchis,gateway,2);
        Painter p3 = new Painter(jButton3,parchis,gateway,3);
        Painter p4 = new Painter(jButton4,parchis,gateway,4);
        p1.start();
        p2.start();
        p3.start();
        p4.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Colores");

        jButton5.setText("Detener");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jButton5)
                .addContainerGap(374, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jButton5)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(816, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
    }     
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { 
        if(!buttonPressed) //If not pressed
        {                 
            buttonPressed =true;             //we change it to pulsed
            
            gateway.close(1);    //Close the gateway for paiters
        }
        else //If it had already been pressed
        {                           
            buttonPressed =false;            //we change
           
            gateway.open(1);    //Open the gateway for paiters
        }
       
    }    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        if(!buttonPressed2) //If not pressed
        {                 
            buttonPressed =true;             //we change it to pulsed
            
            gateway.close(2);    //Close the gateway for paiters
        }
        else //If it had already been pressed
        {                           
            buttonPressed =false;            //we change
            
            gateway.open(2);    //Open the gateway for paiters
        }
       
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { 
        if(!buttonPressed3) //If not pressed
        {                 
            buttonPressed =true;             //we change it to pulsed
            
            gateway.close(3);    //Close the gateway for paiters
        }
        else //If it had already been pressed
        {                           
            buttonPressed =false;            //we change
            
            gateway.open(3);    //Open the gateway for paiters
        }
       
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if(!buttonPressed4) //If not pressed
        {                 
            buttonPressed =true;             //we change it to pulsed
           
            gateway.close(4);    //Close the gateway for paiters
        }
        else //If it had already been pressed
        {                           
            buttonPressed =false;            //we change
            
            gateway.open(4);    //Open the gateway for paiters
        }
    }
    
    
    
    
    
    

    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                new Colours().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration                   
}
